### ISSUE TITLE
Build the CSS file in the server. Does it worth?

### ISSUE THREAD

**Issue by ziogaschr** [osuushi/lemon-soda#2]
Hello @osuushi,
your plugin is very interesting and you did nice work with your code. :)

I was thinking why you don't to build the CSS in the server and load it from the HTML. In this way you will benefit from:
1. processing time in JS
2. no need to load the JS file in the frontend

**Comment by osuushi** [comment]
The reason for not doing that is that browsers block page rendering until all external CSS files have loaded. So if you bloat a style sheet with large data URIs, you'll drastically increase the delay before anything shows up on the screen.

Using AJAX to load the images means that the page renders before the sprites finish loading (the same way it will with ordinary sprite sheets). The reason for loading it as JSON instead of CSS is that it's more flexible, and leaves open the possibility of some other features I'm considering for the future.

As for processing time, it's actually pretty negligible. I expected there to be some hot spots to optimize, but when I measured it, even with relatively large images, the total time between the download and adding the last CSS rule was consistently well under 10 ms.

**Comment by ziogaschr** [comment]
This is a very good point. I haven't thought of it at the first sight.
Indeed it is really fast, in oppose to CSS sprites.
